// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingEngine.Infrastructure.Persistence;

#nullable disable

namespace TradingEngine.Infrastructure.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    [Migration("20260704202322_M34_InitialStopLoss")]
    partial class M34_InitialStopLoss
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("TradingEngine.Infrastructure.Persistence.Entities.AddOnPackEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddOnsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RegimeDetectionEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AddOnPacks", (string)null);
                });

            modelBuilder.Entity("TradingEngine.Infrastructure.Persistence.Entities.BacktestRunEntity", b =>
                {
                    b.Property<string>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlgoHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BacktestFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BacktestTo")
                        .HasColumnType("TEXT");

                    b.Property<double>("BarsPerSec")
                        .HasColumnType("REAL");

                    b.Property<double>("CommissionPerMillion")
                        .HasColumnType("REAL");

                    b.Property<decimal>("CommissionTotal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigSetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DatasetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EffectiveConfigJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GovernorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GrossPnL")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InitialBalance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxDrawdownPct")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetProfit")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Periods")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RegimeEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportJsonPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RunPlanJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Seed")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SpreadPips")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyParamsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SwapTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbols")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalBars")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTrades")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Venue")
                        .HasColumnType("TEXT");

                    b.Property<long>("WallElapsedMs")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WinRatePct")
                        .HasColumnType("REAL");

                    b.Property<int>("WinningTrades")
                        .HasColumnType("INTEGER");

                    b.HasKey("RunId");

                    b.HasIndex("StartedAtUtc");

                    b.ToTable("BacktestRuns", (string)null);
                });

            modelBuilder.Entity("TradingEngine.Infrastructure.Persistence.Entities.BarEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Close")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("High")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Low")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Open")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpenTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("Volume")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "Symbol", "Timeframe", "OpenTimeUtc");

                    b.ToTable("Bars", (string)null);
                });

            modelBuilder.Entity("TradingEngine.Infrastructure.Persistence.Entities.ConfigSetEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.ToTable("ConfigSets", (string)null);
                });

            modelBuilder.Entity("TradingEngine.Infrastructure.Persistence.Entities.DatasetEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FromUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Granularity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RowCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbols")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Timeframes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ToUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.ToTable("Datasets", (string)null);
                });

            modelBuilder.Entity("TradingEngine.Infrastructure.Persistence.Entities.EngineEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("OccurredAtUtc");

                    b.ToTable("EngineEvents", (string)null);
                });

            modelBuilder.Entity("TradingEngine.Infrastructure.Persistence.Entities.EquitySnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentDailyDrawdown")
                        .HasColumnType("REAL");

                    b.Property<decimal>("CurrentMaxDrawdown")
                        .HasColumnType("REAL");

                    b.Property<decimal>("DailyStartEquity")
                        .HasColumnType("REAL");

                    b.Property<decimal>("Equity")
                        .HasColumnType("REAL");

                    b.Property<decimal>("FloatingPnL")
                        .HasColumnType("REAL");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PeakEquity")
                        .HasColumnType("REAL");

                    b.Property<string>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("EquitySnapshots", (string)null);
                });

            modelBuilder.Entity("TradingEngine.Infrastructure.Persistence.Entities.ExperimentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hypothesis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Experiments", (string)null);
                });

            modelBuilder.Entity("TradingEngine.Infrastructure.Persistence.Entities.ExperimentRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BacktestRunId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExperimentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoldIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FoldRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScoreJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("VariantLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BacktestRunId");

                    b.HasIndex("ExperimentId");

                    b.ToTable("ExperimentRuns", (string)null);
                });

            modelBuilder.Entity("TradingEngine.Infrastructure.Persistence.Entities.GovernorOptionsEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GovernorOptions", (string)null);
                });

            modelBuilder.Entity("TradingEngine.Infrastructure.Persistence.Entities.JournalEntryEntity", b =>
                {
                    b.Property<string>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Seq")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("EffectKinds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EffectsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Regime")
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SimTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerdictsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RunId", "Seq");

                    b.HasIndex("RunId", "SimTimeUtc");

                    b.ToTable("Journal", (string)null);
                });

            modelBuilder.Entity("TradingEngine.Infrastructure.Persistence.Entities.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FillPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FilledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FilledLots")
                        .HasColumnType("TEXT");

                    b.Property<string>("LimitPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RequestedLots")
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskProfileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("StopLoss")
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TakeProfit")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("State");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("TradingEngine.Infrastructure.Persistence.Entities.PositionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentStopLoss")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExitReason")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Lots")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpenedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TakeProfit")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Positions", (string)null);
                });

            modelBuilder.Entity("TradingEngine.Infrastructure.Persistence.Entities.PropFirmRuleSetEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PropFirmRuleSets", (string)null);
                });

            modelBuilder.Entity("TradingEngine.Infrastructure.Persistence.Entities.RiskProfileEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RiskProfiles", (string)null);
                });

            modelBuilder.Entity("TradingEngine.Infrastructure.Persistence.Entities.StrategyConfigEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderEntryJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PositionManagementJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReentryJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegimeFilterJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskProfileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("StrategyConfigs", (string)null);
                });

            modelBuilder.Entity("TradingEngine.Infrastructure.Persistence.Entities.TradeResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ClosedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CommissionAmount")
                        .HasColumnType("REAL");

                    b.Property<string>("CommissionCurrency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("EntryReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryRegime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntrySnapshotJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExitDetailJson")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExitPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("ExitReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossPnLAmount")
                        .HasColumnType("REAL");

                    b.Property<string>("GrossPnLCurrency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("InitialStopLoss")
                        .HasColumnType("REAL");

                    b.Property<decimal>("Lots")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxAdverseExcursion")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxFavorableExcursion")
                        .HasColumnType("REAL");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetPnLAmount")
                        .HasColumnType("REAL");

                    b.Property<string>("NetPnLCurrency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpenedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderEntryMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<double>("PnLPips")
                        .HasColumnType("REAL");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("TEXT");

                    b.Property<double>("RMultiple")
                        .HasColumnType("REAL");

                    b.Property<string>("RiskProfileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StopLoss")
                        .HasColumnType("REAL");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SwapAmount")
                        .HasColumnType("REAL");

                    b.Property<string>("SwapCurrency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TakeProfit")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClosedAtUtc");

                    b.HasIndex("RunId");

                    b.HasIndex("StrategyId");

                    b.ToTable("TradeResults", (string)null);
                });

            modelBuilder.Entity("TradingEngine.Infrastructure.Persistence.Entities.VenueSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("RunId");

                    b.ToTable("VenueSessions", (string)null);
                });

            modelBuilder.Entity("TradingEngine.Infrastructure.Persistence.Entities.ExperimentRunEntity", b =>
                {
                    b.HasOne("TradingEngine.Infrastructure.Persistence.Entities.ExperimentEntity", "Experiment")
                        .WithMany("Runs")
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experiment");
                });

            modelBuilder.Entity("TradingEngine.Infrastructure.Persistence.Entities.ExperimentEntity", b =>
                {
                    b.Navigation("Runs");
                });
#pragma warning restore 612, 618
        }
    }
}
