# set-build-stamp.ps1 — Generates a build-info.ts so the Angular UI can show which version is running.
param([string]$OutDir = "src/app/core")

$now = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss zzz")
$commit = try { git rev-parse --short HEAD 2>$null } catch { "unknown" }
$branch = try { git branch --show-current 2>$null } catch { "unknown" }

$content = @"
// Auto-generated by scripts/set-build-stamp.ps1 — DO NOT EDIT.
export const BUILD_TIMESTAMP = '$now';
export const BUILD_COMMIT = '$commit';
export const BUILD_BRANCH = '$branch';
"@

$outFile = Join-Path $OutDir "build-info.ts"
$content | Set-Content $outFile -Encoding UTF8
Write-Host "Build stamp: $now ($commit) -> $outFile"
