# stamp-cbot-build.ps1 — Auto-stamps git hash + date into BuildInfo.g.cs so the cBot shows
# its exact version in cTrader Desktop's parameter panel and log output.
param([string]$OutDir = "src\TradingEngine.Adapters.CTrader")

$hash = try { git rev-parse --short HEAD 2>$null } catch { "unknown" }
$date = (Get-Date).ToString("yyyy-MM-dd")
$branch = try { git branch --show-current 2>$null } catch { "unknown" }

$stamp = "v2.0.0 $date $hash $branch"

$content = @"
// Auto-generated by scripts/stamp-cbot-build.ps1 — DO NOT EDIT.
// Regenerated on every build. Shows in cTrader Desktop's _build parameter.
namespace TradingEngine.Adapters.CTrader;
partial class TradingEngineCBot
{
    internal const string CbotBuildStamp = "$stamp";
}
"@

$outFile = Join-Path $OutDir "BuildInfo.g.cs"
$content | Set-Content $outFile -Encoding UTF8
Write-Host "cBot stamp: $stamp -> $outFile"
