// Auto-generated by scripts/stamp-cbot-build.ps1 â€” DO NOT EDIT.
// Regenerated on every build. Shows in cTrader Desktop's _build parameter.
namespace TradingEngine.Adapters.CTrader;
partial class TradingEngineCBot
{
    internal const string CbotBuildStamp = "v2.0.0 2026-07-06 dc4e58c iter/quant-model--p1-tf-agnostic";
}
