using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Text.Json;
using cAlgo.API;
using cAlgo.API.Internals;
using NetMQ;
using NetMQ.Sockets;

namespace TradingEngine.Adapters.CTrader;

[Robot(AccessRights = AccessRights.FullAccess)]
public partial class TradingEngineCBot : Robot
{
    // Build stamp is auto-generated by scripts/stamp-cbot-build.ps1 (run before build).
    // Shows as a read-only parameter in cTrader Desktop so you know which version is loaded.
    [Parameter("_build", DefaultValue = CbotBuildStamp)]
    public string BuildInfo { get; set; } = CbotBuildStamp;

    [Parameter("DataPort", DefaultValue = "15555")]
    public int DataPort { get; set; } = 15555;

    [Parameter("CommandPort", DefaultValue = "15556")]
    public int CommandPort { get; set; } = 15556;

    [Parameter("TickEveryN", DefaultValue = "10")]
    public int TickEveryN { get; set; } = 10;

    [Parameter("SymbolString", DefaultValue = "EURUSD")]
    public string SymbolString { get; set; } = "EURUSD";

    [Parameter("Periods", DefaultValue = "H1")]
    public string Periods { get; set; } = "H1";

    // Directory where the cBot writes its OWN report.json + events.json (our resilient venue ledger,
    // replacing cTrader-cli's crashing --report-json). Empty = disabled.
    [Parameter("ReportPath", DefaultValue = "")]
    public string ReportPath { get; set; } = "";

    [Parameter("Diagnostics", DefaultValue = "false")]
    public bool Diagnostics { get; set; } = false;

    [Parameter("Verbose", DefaultValue = "false")]
    public bool Verbose { get; set; } = false;

    // iter-marketdata-tape P2 — recorder mode. When true, the cBot does NOT talk to the engine; it runs as a
    // plain backtest and appends every closed bar to an NDJSON shard under ReportPath (MarketDataShardIo
    // format), reusing cTrader's own replay to page history at any timeframe. Default false = normal engine run.
    [Parameter("Record", DefaultValue = "false")]
    public bool Record { get; set; } = false;

    private PublisherSocket? _pub;
    private DealerSocket? _dealer;
    private NetMQPoller? _poller;
    private readonly BlockingCollection<string> _inbox = new();
    private readonly ConcurrentQueue<Action> _mainActions = new();
    private int _tickCounter;
    private int _barEventCount;
    private int _duplicateCount;
    private int _cmdsReceived;
    private int _ordersExecuted;
    private int _execsSent;
    private readonly HashSet<(string symbol, string tf, DateTime openTime)> _publishedBars = new();
    private readonly List<Bars> _subscriptions = new();
    private readonly Dictionary<long, Guid> _positionMap = new();
    private readonly HashSet<long> _commandCloses = new();
    // key = clientOrderId. Tracks BOTH resting Limit and Stop entry orders (P2.7) — expiry/cancel logic
    // is identical for either kind, so one dict/class covers both.
    private readonly Dictionary<string, PendingEntryOrder> _pendingEntryOrders = new();
    private volatile bool _connected;

    private sealed class PendingEntryOrder
    {
        public int BarsRemaining;
        public string Symbol = "";
        // F33: kept so the fill handler can verify the venue actually honoured the protection prices
        // the resting order was placed with.
        public double? StopLoss;
        public double? TakeProfit;
    }

    private readonly ShamshirTradeLogger _tradeLog = new();
    private int _reportCheckpoint;
    private const int ReportCheckpointEveryNBars = 50;

    private long _timingRoundTrips;
    private long _timingRoundTripTotalMs;
    private long _timingRoundTripMaxMs;
    private long _timingBarProcTotalMs;
    private long _timingCheckpointTotalMs;
    private long _timingTickPublishCount;

    // iter-marketdata-tape P2 — recorder mode state (only used when Record=true).
    private readonly Dictionary<string, System.IO.StreamWriter> _shardWriters = new();
    private long _recordedBars;

    private static long EpochMs(DateTime utc) =>
        new DateTimeOffset(DateTime.SpecifyKind(utc, DateTimeKind.Utc)).ToUnixTimeMilliseconds();

    private static readonly JsonSerializerOptions JsonOpts = new()
    { PropertyNamingPolicy = JsonNamingPolicy.CamelCase };

    private void Diag(string msg)
    {
        if (_pub is null) return;
        _pub.SendMoreFrame("diag").SendFrame(msg);
    }

    protected override void OnStart()
    {
        Print($"CBOT|START|symbol={SymbolName}|tf={TimeFrame.ShortName}|dataPort={DataPort}|cmdPort={CommandPort}|build={CbotBuildStamp}|mode={(IsBacktesting ? "backtest" : "live")}");

        // iter-marketdata-tape P2: recorder mode short-circuits the whole engine path — no NetMQ, no handshake.
        if (Record) { StartRecording(); return; }

        _tradeLog.Symbol = SymbolName;
        _tradeLog.Period = TimeFrame.ShortName;
        _tradeLog.StartingCapital = Account.Balance;
        _tradeLog.AccountCurrency = Account.Asset.Name;
        _tradeLog.RecordEquity(Account.Balance, Account.Equity, EpochMs(Server.TimeInUtc));
        if (!string.IsNullOrWhiteSpace(ReportPath))
            Print($"CBOT|REPORT_PATH|{ReportPath}");

        _pub = new PublisherSocket();
        _pub.Bind($"tcp://*:{DataPort}");
        Print($"CBOT|PUB_BOUND|dataPort={DataPort}");

        _dealer = new DealerSocket();
        _dealer.Connect($"tcp://127.0.0.1:{CommandPort}");
        _dealer.ReceiveReady += OnDealerReceive;

        _poller = new NetMQPoller { _dealer };
        _poller.RunAsync();

        var symbols = SymbolString.Split(',', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries);
        var periods = Periods.Split(',', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries);
        var subs = new List<(string sym, string tf)>();
        for (int i = 0; i < symbols.Length; i++)
        {
            var sym = symbols[i];
            var period = i < periods.Length ? periods[i] : periods[^1];
            var tf = ParseTimeFrame(period);
            var bars = MarketData.GetBars(tf, sym);
            _subscriptions.Add(bars);
            subs.Add((sym, period));
        }

        Print($"CBOT|SUBS|{string.Join(", ", subs.Select(s => $"{s.sym}:{s.tf}"))}");

        // V1/V2 — rebuild the Guid↔venue-id map from existing positions (durable Guid in Comment)
        // and announce the open-position snapshot in the hello so the engine can reconcile.
        RebuildPositionMap();
        var positionSnapshot = BuildPositionSnapshot();

        var helloMsg = Serialize("hello", new
        {
            v = 2,
            symbols = symbols,
            periods = periods,
            subs = subs.Select(s => new { s.sym, tf = s.tf }).ToArray(),
            barsLoaded = _subscriptions.Sum(s => s.Count),
            // F34: the account's currency was never declared, so nobody noticed the venue account is
            // EUR-denominated while the whole engine models USD — a silent 0.8638 scaling on every
            // cTrader money figure ever produced.
            account = new { balance = Account.Balance, equity = Account.Equity, currency = Account.Asset.Name },
            positions = positionSnapshot,
            mode = IsBacktesting ? "backtest" : "live"
        });
        _dealer.SendFrame(helloMsg);
        Print($"CBOT|HELLO_SENT|subs={subs.Count}|barsLoaded={_subscriptions.Sum(s => s.Count)}|ccy={Account.Asset.Name}|mode={(IsBacktesting ? "backtest" : "live")}");

        for (int retry = 0; retry < 50 && !_connected; retry++)
        {
            if (retry > 0 && retry % 10 == 0)
            {
                _dealer.SendFrame(helloMsg);
                Print($"CBOT|HELLO_RESEND|retry={retry}");
            }
            System.Threading.Thread.Sleep(100);
        }

        if (!_connected)
        {
            Print("CBOT|HELLO_TIMEOUT|engine did not acknowledge hello — stopping");
            Stop();
            return;
        }

        Print($"CBOT|HANDSHAKE_COMPLETE|connected");

        // Emit venue symbol specs so the engine can adopt the broker's real economics (D10).
        var emittedSpecs = new HashSet<string>();
        foreach (var sym in symbols)
        {
            if (!emittedSpecs.Add(sym)) continue;
            try
            {
                var spec = Symbols.GetSymbol(sym);
                var specMsg = Serialize("symbol_spec", new
                {
                    v = 1,
                    symbol = sym,
                    commission = (double)spec.Commission,
                    commissionType = spec.CommissionType.ToString(),
                    swapLong = (double)spec.SwapLong,
                    swapShort = (double)spec.SwapShort,
                    swapCalculationType = spec.SwapCalculationType.ToString(),
                    lotSize = (double)spec.LotSize,
                    pipSize = (double)spec.PipSize,
                    tickSize = (double)spec.TickSize,
                    tickValue = (double)spec.TickValue,
                    digits = spec.Digits,
                    tripleSwapDay = "Wednesday",
                    spread = (double)spec.Spread
                });
                _dealer.SendFrame(specMsg);
                Print($"CBOT|SYMBOL_SPEC|symbol={sym}|commType={spec.CommissionType}|comm={spec.Commission:F4}|swapL={spec.SwapLong:F4}|swapS={spec.SwapShort:F4}");
            }
            catch (Exception ex)
            {
                Print($"CBOT|SYMBOL_SPEC_ERROR|symbol={sym}|err={ex.Message}");
            }
        }

        foreach (var (sym, period) in subs)
        {
            var tf = ParseTimeFrame(period);
            var bars = MarketData.GetBars(tf, sym);
            bars.BarClosed += OnBarClosed;
        }

        if (Verbose) Diag($"SUBSCRIBED|subs={subs.Count}");
        Print($"CBOT|SUBSCRIBED|subs={subs.Count}");

        Positions.Closed += OnPositionClosed;
        Positions.Opened += OnPositionOpened;

        PublishAccount();

        Print($"CBOT|READY|dataPort={DataPort}|cmdPort={CommandPort}");
    }

    protected override void OnTick()
    {
        _tickCounter++;

        if (_tickCounter % TickEveryN == 0 && Verbose)
        {
            Publish("tick", new
            {
                symbol = SymbolName,
                bid = Symbol.Bid,
                ask = Symbol.Ask,
                time = Server.TimeInUtc.ToString("o")
            });

            PublishAccount();
            _timingTickPublishCount++;
        }
    }

    private void TryWriteReport()
    {
        if (string.IsNullOrWhiteSpace(ReportPath)) return;
        try { _tradeLog.Write(ReportPath, Account.Balance, Account.Equity); }
        catch (Exception ex) { Print($"CBOT|REPORT_WRITE_ERR|{ex.Message}"); }
    }

    protected override void OnStop()
    {
        // iter-marketdata-tape P2: recorder mode has no engine/sockets — just flush the shards and finish.
        if (Record) { StopRecording(); return; }

        // Flush our ledger FIRST — before any NetMQ teardown and before cTrader's own (crash-prone)
        // report-saving runs — so report.json/events.json are always written even if cTrader dies after.
        TryWriteReport();

        Diag($"STOP|ticks={_tickCounter}|barEvents={_barEventCount}|dup={_duplicateCount}");
        Print($"CBOT|STOP|ticks={_tickCounter}|barEvents={_barEventCount}|dup={_duplicateCount}");

        if (Diagnostics && _timingRoundTrips > 0)
        {
            var mean = _timingRoundTripTotalMs / (double)_timingRoundTrips;
            Print($"CBOT|TIMING|bars={_timingRoundTrips}|roundTrip(ms) total={_timingRoundTripTotalMs} mean={mean:F1} max={_timingRoundTripMaxMs}|barProc(ms)={_timingBarProcTotalMs}|ckpt(ms)={_timingCheckpointTotalMs}|tickPubs={_timingTickPublishCount}|ticks={_tickCounter}");
        }

        while (_mainActions.TryDequeue(out var action))
        {
            try { action(); }
            catch (Exception ex) { Print($"CBOT|DRAIN_ERR|{ex.Message}"); }
        }

        var stats = Serialize("stats", new
        {
            v = 1,
            barsSent = _barEventCount,
            cmdsReceived = _cmdsReceived,
            ordersExecuted = _ordersExecuted,
            execsSent = _execsSent
        });
        try { _dealer?.SendFrame(stats); } catch (Exception ex) { Print($"CBOT|STATS_SEND_FAIL|ex={ex.Message}"); }

        if (_dealer is not null) _dealer.Options.Linger = TimeSpan.FromSeconds(2);
        if (_pub is not null) _pub.Options.Linger = TimeSpan.FromSeconds(2);

        _poller?.StopAsync();
        _dealer?.Dispose();
        _pub?.Dispose();
        _poller?.Dispose();

        try { NetMQConfig.Cleanup(true); }
        catch { NetMQConfig.Cleanup(false); }
    }

    private static TimeFrame ParseTimeFrame(string s) => s.ToUpperInvariant() switch
    {
        "M1" => TimeFrame.Minute,
        "M5" => TimeFrame.Minute5,
        "M15" => TimeFrame.Minute15,
        "M30" => TimeFrame.Minute30,
        "H1" => TimeFrame.Hour,
        "H4" => TimeFrame.Hour4,
        "D1" => TimeFrame.Daily,
        "W1" => TimeFrame.Weekly,
        _ => throw new ArgumentException($"Unknown timeframe: {s}")
    };

    private void Publish(string topic, object payload)
    {
        if (_pub is null) return;
        try
        {
            var json = Serialize(topic, payload);
            _pub.SendMoreFrame(topic).SendFrame(json);
        }
        catch (Exception ex)
        {
            Print($"CBOT|PUB_ERR|{topic}|{ex.Message}");
        }
    }

    private void PublishAccount()
    {
        Publish("acct", new
        {
            balance = Account.Balance,
            equity = Account.Equity,
            floatingPnL = Account.Equity - Account.Balance,
            time = Server.TimeInUtc.ToString("o")
        });
    }

    private static string Serialize(string type, object payload)
    {
        var node = JsonSerializer.SerializeToNode(payload, payload.GetType(), JsonOpts)!.AsObject();
        node["type"] = type;
        return node.ToJsonString(JsonOpts);
    }
}
