// Auto-generated by scripts/set-build-stamp.ps1 â€” DO NOT EDIT.
export const BUILD_TIMESTAMP = '2026-07-02 19:22:12 +01:00';
export const BUILD_COMMIT = '4bd9f4f';
export const BUILD_BRANCH = 'develop';
