// Auto-generated by scripts/set-build-stamp.ps1 â€” DO NOT EDIT.
export const BUILD_TIMESTAMP = '2026-06-30 13:01:26 +01:00';
export const BUILD_COMMIT = '1d98478';
export const BUILD_BRANCH = 'iter/redesign-ctrader';
